---
- hosts: all
  tasks:
  - name: install http package
    yum:
      name: httpd
      state: latest
    notify: restart httpd
    
  handlers:
    - name: restarted httpd
      service:
        name: httpd
        state: restarted
