---
- hosts: all
  tasks:
  - name: create a cache directory
    file:
      path: /opt/cache
      state: directory
  
  - name: install xclock
    yum:
      name: xclock
      state: latest
  
  - name: remove xclock
    yum:
      name: xclock
      state: absent
      
