---
- hosts: all
  tasks:
  - name: create a cache directory
    file:
      path: /opt/cache
      state: directory
  
  - name: install nginx
    yum:
      name: nginx
      state: latest
  
  - name: restart nginx
    service:
      name: nginx
      state: restarted
      
